# Mapping aliases for LLM keys to schema paths.
# Keep values as schema paths used in mapping.SCHEMA_MAP.

KEY_SYNONYMS = {
    "hpi.conceiveMode": ["受孕方式", "受孕途径", "妊娠方式", "自然受孕", "辅助生殖", "试管", "IVF", "IVF-ET"],
    "hpi.chiefcomplaint": ["主诉", "首诊主诉", "就诊主诉", "核心主诉"],

    "hpi.otherNote": ["现病史备注", "现病史补充", "现病史说明", "胎动", "胎动情况", "胎动减少", "胎动频繁", "胆汁酸", "总胆汁酸", "瘙痒开始时间", "瘙痒"],
    "hpi.sureEdd": ["核定预产期", "确认预产期", "核对预产期"],
    "hpi.lmp": ["末次月经", "末次月经时间", "LMP"],
    "hpi.edd": ["预产期", "预产期日期", "EDD"],

    "pmh.hypertension": ["高血压", "高血压史", "高血压病史"],
    "pmh.diabetes": ["糖尿病", "糖尿病史"],
    "pmh.cardiacDisease": ["心脏病", "心脏病史", "心脏疾病", "心脏疾患"],
    "pmh.allergyDrug": ["药物过敏", "药物过敏史", "药物过敏反应"],
    "pmh.allergyFood": ["食物过敏", "食物过敏史"],
    "pmh.allergyOther": ["其他过敏", "过敏史", "过敏体质"],
    "pmh.transfusionHistory": ["输血史", "既往输血史"],
    "pmh.operationHistory": ["手术史", "既往手术史", "外科手术史"],

    "pmh.thyroidDisease": ["甲状腺疾病", "甲状腺", "甲减", "甲亢", "桥本", "甲状腺功能减退", "甲状腺功能亢进"],
    "pmh.otherNote": ["既往史其他", "既往史补充", "既往史备注", "贫血", "癫痫"],

    # 传染病史自 pmh.otherNote 迁出：乙肝/肝炎/梅毒/HIV/结核等统一落位 pmh.infectiousHistory。
    # 检验态 key（乙肝五项/两对半/表面抗原/梅毒抗体/HIV筛查等）故意不收，继续走兜底防检验结果误写成病史。
    "pmh.infectiousHistory": ["传染病史", "传染病", "传染性疾病", "传染病病史",
                              "乙肝", "乙肝病史", "乙型肝炎", "丙肝", "丙型肝炎",
                              "肝炎", "肝炎病史", "梅毒", "梅毒病史",
                              "HIV", "hiv", "艾滋病", "结核", "结核病史", "肺结核"],

    "additional_medical_history.menarche": ["初潮", "月经初潮", "初潮年龄"],
    "additional_medical_history.menstrualCycle": ["月经周期", "经期周期"],
    "additional_medical_history.otherNote": ["月经规律", "月经规律性", "月经"],
    "additional_medical_history.menstrualPeriod": ["行经期", "经期", "月经经期", "行经天数"],
    "additional_medical_history.menstrualVolume": ["月经量", "经量", "月经量评估"],
    "additional_medical_history.dysmenorrhea": ["痛经", "痛经史"],
    "additional_medical_history.maritalStatus": ["婚姻状况", "婚姻状态"],
    "additional_medical_history.maritalYears": ["婚龄", "结婚年限", "结婚年数"],
    "additional_medical_history.nearRelation": ["近亲婚配", "近亲结婚", "近亲婚配史"],

    "personal_history.smoke": ["吸烟史", "吸烟", "抽烟"],
    "personal_history.alcohol": ["饮酒史", "饮酒", "喝酒"],
    "personal_history.hazardoussubstances": ["有害物质接触", "有毒物质接触", "职业暴露", "有害化学物质接触史", "接触有害物质史", "接触有毒化学物质"],
    "personal_history.radioactivity": ["放射性接触", "放射物接触", "放射性物质接触", "放射线接触史", "放射物质接触", "放射物质", "放射线接触"],
    "personal_history.medicine": ["孕期服药史", "个人用药史", "个人服药史", "服药史"],
    "personal_history.otherNote": ["个人史补充", "个人史其他", "个人史备注"],

    "fh.diabetes": ["家族糖尿病", "家族糖尿病史"],
    "fh.hypertension": ["家族高血压", "家族高血压史"],
    "fh.birthdefects": ["出生缺陷史", "家族出生缺陷", "家族畸形", "出生缺陷"],
    "fh.heritableDisease": ["遗传病史", "遗传性疾病", "遗传病"],
    "fh.otherNote": ["家族史补充", "家族史其他", "家族史备注"],

    "physicalExamination.systolic": ["收缩压"],
    "physicalExamination.diastolic": ["舒张压"],
    "physicalExamination.systolic2": ["第二次收缩压", "第二次血压收缩压"],
    "physicalExamination.diastolic2": ["第二次舒张压", "第二次血压舒张压"],
    "physicalExamination.systolic3": ["第三次收缩压", "第三次血压收缩压"],
    "physicalExamination.diastolic3": ["第三次舒张压", "第三次血压舒张压"],
    "physicalExamination.pulse": ["脉搏", "脉率"],
    "physicalExamination.heartrate": ["心率"],
    "physicalExamination.weight": ["体重", "当前体重"],
    "physicalExamination.preheight": ["身高", "孕前身高"],
    "physicalExamination.preweight": ["孕前体重"],
    "physicalExamination.bmi": ["查体BMI", "当前BMI", "体格BMI", "体质指数"],
    "physicalExamination.skin": ["皮肤"],
    "physicalExamination.thyroid": ["甲状腺触诊"],
    "physicalExamination.breast": ["乳房"],
    "physicalExamination.respiratory": ["呼吸节律", "呼吸系统"],
    "physicalExamination.rales": ["肺部啰音", "啰音"],
    "physicalExamination.heartrhythm": ["心律"],
    "physicalExamination.murmurs": ["心脏杂音", "杂音"],
    "physicalExamination.liver": ["肝脏"],
    "physicalExamination.spleen": ["脾脏"],
    "physicalExamination.spine": ["脊柱"],
    "physicalExamination.edema": ["水肿", "下肢水肿", "双下肢水肿", "脚肿", "脚踝肿", "脚踝水肿", "踝部水肿"],
    "physicalExamination.physiologicalreflection": ["生理反射"],
    "physicalExamination.pathologicalreflection": ["病理反射"],
    "physicalExamination.otherNote": ["查体补充", "查体备注", "体格检查补充", "胎儿体重估计", "预估胎儿体重", "胎儿体重"],

    "gynecologicalExamination.fundalHeight": ["宫高", "子宫高度"],
    "gynecologicalExamination.waistHip": ["腹围", "腰臀围"],
    "gynecologicalExamination.engagement": ["衔接", "胎头入盆", "入盆", "衔接情况"],
    "gynecologicalExamination.vulva": ["外阴"],
    "gynecologicalExamination.vagina": ["阴道"],
    "gynecologicalExamination.cervix": ["宫颈"],
    "gynecologicalExamination.uterus": ["子宫"],
    "gynecologicalExamination.adnexa": ["附件", "附件区"],
    "gynecologicalExamination.otherNote": ["妇科检查补充", "专科检查补充"],

    "advice.prescription": ["医嘱", "处方", "医嘱与诊疗计划", "诊疗计划", "医嘱建议", "医嘱内容"],
    "advice.exam": ["检验检查", "检查开立", "开立检查", "检查建议"],
    "advice.appointmentCycle": ["随访周期", "复诊周期"],
    "advice.appointmentType": ["预约类型"],
    "advice.appointmentDate": ["预约日期", "预约具体日期"],
    "advice.appointmentPeriod": ["预约时段"],
    "advice.visitDate": ["复诊日期", "建议复诊日期", "下次就诊时间"],
    "advice.doctorName": ["接诊医生", "医生姓名"]
}

FETUS_FIELD_SYNONYMS = {
    "fetalHeartRate": ["胎心", "胎心率", "FHR"],
    "fetalPosition": ["胎方位", "胎儿方位", "胎方位如", "胎向", "枕位"],
    "position": ["胎位", "头位", "臀位", "横位", "斜位"],
    "presentation": ["先露", "先露部位", "先露位置"],
}

# 中文胎方位 → 专业缩写代码映射
FETAL_POSITION_CN_TO_CODE = {
    "枕左前": "LOA", "左枕前": "LOA",
    "枕右前": "ROA", "右枕前": "ROA",
    "枕左后": "LOP", "左枕后": "LOP",
    "枕右后": "ROP", "右枕后": "ROP",
    "枕左横": "LOT", "左枕横": "LOT",
    "枕右横": "ROT", "右枕横": "ROT",
    "骶左前": "LSA", "左骶前": "LSA",
    "骶右前": "RSA", "右骶前": "RSA",
    "骶左后": "LSP", "左骶后": "LSP",
    "骶右后": "RSP", "右骶后": "RSP",
    "颏左前": "LMA", "左颏前": "LMA",
    "颏右前": "RMA", "右颏前": "RMA",
    "颏左后": "LMP", "左颏后": "LMP",
    "颏右后": "RMP", "右颏后": "RMP",
    "颏左横": "LMT", "左颏横": "LMT",
    "颏右横": "RMT", "右颏横": "RMT",
    "肩左前": "LScA", "左肩前": "LScA",
    "肩右前": "RScA", "右肩前": "RScA",
    "肩左后": "LScP", "左肩后": "LScP",
    "肩右后": "RScP", "右肩后": "RScP",
}
